<script>

	AEC.Const.CHECKOUT_STEP_CART	 = <?php echo \Anowave\Ecopz\Helper\Data::CHECKOUT_STEP_CART ?>;
	AEC.Const.CHECKOUT_STEP_CHECKOUT = <?php echo \Anowave\Ecopz\Helper\Data::CHECKOUT_STEP_CHECKOUT ?>;
	AEC.Const.CHECKOUT_STEP_SHIPPING = <?php echo \Anowave\Ecopz\Helper\Data::CHECKOUT_STEP_SHIPPING ?>;
	AEC.Const.CHECKOUT_STEP_PAYMENT  = <?php echo \Anowave\Ecopz\Helper\Data::CHECKOUT_STEP_PAYMENT ?>;
	AEC.Const.CHECKOUT_STEP_ORDER    = <?php echo \Anowave\Ecopz\Helper\Data::CHECKOUT_STEP_ORDER ?>
</script>