<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}

$relatedProducts = $_product->getRelatedProducts();
?>

<div class="product-details">
    <div class="details-container">
        <?php echo $block->getChildHtml('product.category.image'); ?>
        <?php if ($_attributeValue): ?>
            <div class="product attribute <?php /* @escapeNotVerified */ echo $_className?>">
                <?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?></strong><?php endif; ?>
                <div class="value" <?php /* @escapeNotVerified */ echo $_attributeAddAttribute;?>><?php /* @escapeNotVerified */ echo $_attributeValue; ?></div>
            </div>
        <?php endif; ?>

        <?php echo $block->getChildHtml('product.details.material.description', true) ?>

        <?php echo $block->getChildHtml('product.details.qualifications', true) ?>
        <?php echo $block->getChildHtml('product.details.features', true) ?>
    </div>
    <?php 
    		if($block->getRequest()->getParam('secure')){
    		echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
	    								  ->setBlockId($block->getProduct()->getMaterialWhatsIncluded())
										  ->toHtml();
			}else{
    		echo $block->getChildHtml('catalog.product.related', true);
    		} 
    		
    
    
    
    
    
    ?>
</div>