<?php 
$URLelements = explode('/', $block->getRequest()->getRequestUri());
if($URLelements[1] == 'pwc-covers'):

function modelTextCorrect($modelText){
	$modelTextArray = explode('-', $modelText); 
	$newModel = '';                
		
	foreach ($modelTextArray as $modelValue){   
		if (preg_match('/[a-z]+[0-9]+/', $modelValue) || preg_match('/[0-9]+[a-z]+/', $modelValue)){$newModel .= ' '.strtoupper($modelValue);
		}elseif (preg_match('/\b\w{1,3}\b/', $modelValue)){$newModel .= ' '.strtoupper($modelValue);
		}else {$newModel .= ' '.ucwords($modelValue);}
	}
	return $newModel;
}

$yearURL = ucwords(str_replace('-', ' ', $URLelements[2])); // Sometimes year = all-years
$makeURL = ucwords(str_replace('-', ' ', $URLelements[3]));
$modelURL = modelTextCorrect($URLelements[4]);

?>          
	<div class="title-container">
	    <h1><?php echo $yearURL.' '.$makeURL.' '.$modelURL.' '.$this->getProduct()->getMaterialFinalName() ?></h1>
	    <p class="subtitle"><?php echo $this->getProduct()->getShortDescription(); ?></p>
	</div>

	<?php else: ?>   
	<div class="title-container">
	    <h1><?php echo $this->getProduct()->getMaterialFinalName(); ?></h1>
	    <p class="subtitle"><?php echo $this->getProduct()->getShortDescription(); ?></p>
	</div>
 <?php endif; ?>