<div class="logos">
    <div class="cards">
        <p class="title"><?php echo __('We Gladly Accept') ?></p>
        <img src="<?php echo $this->getViewFileUrl('images/cc.png'); ?>" />
    </div>
    <div class="retailers">
        <img src="<?php echo $this->getViewFileUrl('images/retailers.png'); ?>" />
    </div>
    <div class="safe-shopping">
        <p class="title"><?php echo __('Safe & Secure Shopping') ?></p>
        <img src="<?php echo $this->getViewFileUrl('images/comodo_secure_seal.png'); ?>" />
    </div>
</div>
<div class="clearfix"></div>