<div class="cms-left-links">
    <div class="section">
        <p class="title"><?php echo __('Our Company'); ?></p>
        <ul class="links">
            <li><a href="<?php echo $this->getBaseUrl().'about_us'; ?>"><?php echo __('About Us') ?></a></li>
            <li><a href="javascript::void(0)" class="best-price"><?php echo __('Best Price Guarantee') ?></a></li>
            <li><a href="javascript::void(0)" class="custom-fit"><?php echo __('Custom Fit') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'contact'; ?>"><?php echo __('Contact Us') ?></a></li>
        </ul>
    </div>
    <div class="section">
        <p class="title"><?php echo __('Help Center'); ?></p>
        <ul class="links">
            <li><a href="<?php echo $this->getBaseUrl().'faq'; ?>"><?php echo __('FAQs') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'sales/guest/form/'; ?>"><?php echo __('Order Status') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'return_center'; ?>"><?php echo __('Return Center') ?></a></li>
        </ul>
    </div>
    <div class="section">
        <p class="title"><?php echo __('Our Policies'); ?></p>
        <ul class="links">
            <li><a href="<?php echo $this->getBaseUrl().'return_policy'; ?>"><?php echo __('Return Policy') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'cancellation_policy'; ?>"><?php echo __('Cancellation Policy') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'warranty_policy'; ?>"><?php echo __('Warranty Policy') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'privacy_policy'; ?>"><?php echo __('Privacy Policy') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'security_policy'; ?>"><?php echo __('Security Policy') ?></a></li>
            <li><a href="<?php echo $this->getBaseUrl().'shipping_policy'; ?>"><?php echo __('Shipping Policy') ?></a></li>
        </ul>
    </div>
</div>