<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Finder
 */
?>
<?php
/**
 * Copyright © 2015 Amasty. All rights reserved.
 */
/**
 * @var $block \Amasty\Finder\Block\Form
 */
?>
<?php $finderId = 'amfinder_' . uniqid(); ?>
<form method="post" action="<?php echo $block->getActionUrl() ?>" data-mage-init='{"validation": {}}'>
    <div class="amfinder-vertical" id="<?php echo $finderId ?>Container">
        <input type="hidden" name="finder_id" value="<?php echo $block->getId() ?>"/>
        <input type="hidden" name="back_url" value="<?php echo $block->getBackUrl() ?>"/>
        <input type="hidden" name="category_id" value="<?php echo $block->getCurrentCategoryId() ?>"/>
        <?php foreach ($block->getFinder()->getDropdowns() as $dropdown): ?>
            <div class="dropdown-title"><?php echo __($block->escapeHtml($dropdown->getName())) ?></div>
            <div class="dropdown-element amshopby-clearer">
                <select data-validate="{required:true, 'validate-filter-field':true}"  <?php echo $block->getDropdownAttributes($dropdown)?> style="width:200px">
                    <?php foreach($block->getDropdownValues($dropdown) as $v): ?>
                        <option value="<?php echo $v['value'] ?>"<?php if ($v['selected']):?>selected="selected"<?php endif ?>>
                            <?php echo $block->escapeHtml($v['label']) ?>
                        </option>
                    <?php endforeach ?>
                </select>
            </div>
        <?php endforeach ?>
        <div class="amfinder-buttons" style="display:<?php echo ($block->isButtonsVisible() ? 'block' : 'block')?>">
            <button class="button action primary" title="<?php echo __('View Covers Now') ?>" type="submit"><span><span><?php echo __('View Covers Now') ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    require(['jquery', 'Amasty_Finder/js/amfinder'], function($) {
        var finderConfig = <?php echo $block->getJsonConfig(); ?>;
        finderConfig.containerId = '<?php echo $finderId ?>Container';
        finderConfig.loadingText = '<?php echo __('Loading...')?>';
        $("#<?php echo $finderId ?>Container").amfinder(finderConfig);
    });
</script>    
<script type="text/javascript">
require([
    'jquery', // jquery Library
    'jquery/ui', // Jquery UI Library
    'jquery/validate', // Jquery Validation Library
    'mage/translate' // Magento text translate (Validation message translte as per language)
    ], function($){ 
    $.validator.addMethod(
    'validate-filter-field', function (value) { 
        return (value !== '0'); // Validation logic here
    }, $.mage.__('Please choose all filters'));

    });
    </script>
