<?php 
	   
	if(!$block->getRequest()->getParam('find')): 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current category  
  $_page_config = $objectManager->get('Magento\Framework\View\Page\Config');
  
	$isRobot = ((strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "googlebot") OR $block->getRequest()->getParam('isRobotTest')))?TRUE:FALSE;
	$currentPageTitle = preg_replace('/\s+/', ' ',$_page_config->getTitle()->getShort());
	$currentCategory = $block->getCurrentCategory(); 
	$categoryTitle = $currentCategory->getName();   
	$categoryLevel = $block->getCurrentCategory()->getLevel(); 
	$maxChildLevel = $block->getMaxChildLevel(); 
	$categoryHelper = $block->getCategoryHelper(); 
	$parentCategories = $block->getParentCategories(); 
	$categoryID = $category->getId();

	$isPrimaryCategory = ($categoryID == 3 || $categoryID == 4 || $categoryID == 5 || $categoryID == 6) ? TRUE : FALSE;    
	
	$subtitle = 'Shop by';
	$subtitle .= str_replace('Select', '', $block->getFirstStepTitle());
        if($maxChildLevel == 4):
            $subtitle .= ' and Size ';
        endif;
        $subtitle .= ' instead';
    ?>
    <a name="Category"></a><a name="Model"></a><a name="Year"></a><a name="Option"></a>
    <h1><?php echo $currentPageTitle; ?></h1>
    <p>&nbsp;</p>

    <?php if(!$isPrimaryCategory): ?>
            <div class="boat-type">
                <p class="name"><?php echo $currentCategory->getName() ?></p>
                <div class="img-container">
                <?php 
                		if(!$currentCategory->getImageUrl()){
                			$categoryBranch = explode('/', str_replace('1/2/', '', $currentCategory->getPath()));
                			$categoryBranch = array_reverse($categoryBranch);
                			foreach($categoryBranch AS $categoryBranchID){
                				if($finalCategoryImage = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryBranchID)->getImageUrl()){break;}
                			}
                		}else{
                			$finalCategoryImage = $currentCategory->getImageUrl();
                		}
                ?> 
                <img src="<?php echo $finalCategoryImage; ?>" />
                </div>
            </div> 
            <div class="material-description">                                 
								<?php echo $currentCategory->getDescription(); ?>
                <a href="<?php if($isRobot){echo '#';}else{echo $currentCategory->getParentCategory()->getUrl().'#'.$currentCategory->getcontent_subtitle();} ?>" class="action primary">
                    <span class="change-model">Change <?php echo $currentCategory->getcontent_subtitle(); ?></span>
                </a>
                <div class="made-in-usa">
                    <img src="<?php echo $this->getViewFileUrl('images/made-in-usa.png'); ?>" />
                </div>
            </div>
    <?php endif; ?>
    <?php
        $i = 0;
        $columnsClass = $block->getColumnsClass();
        $subCategories = $block->getSubcategories(); 
		    
		    if($objectManager->create('Magento\Catalog\Model\Category')->load($subCategories->getFirstItem()->getId())->getImageUrl()): ?>
		    		<ul class="category-grid">
		    <?php else: ?>  
		    		<ul class="category-grid2">
		    <?php endif; ?>  
		                                  
    			<?php if(!$isPrimaryCategory && count($subCategories)>0): ?>
    			<h2>Select <?php echo $selectType = $objectManager->create('Magento\Catalog\Model\Category')->load($subCategories->getFirstItem()->getId())->getcontent_subtitle(); ?></h2>
        <?php endif; ?>
        
        <?php          
        
        foreach($subCategories as $subCategory):
            $i++;
            
            if($subCategory->getName()=='makes'){
                echo '</ul>';
                echo '<ul class="category-grid">';
                echo '<p class="title">Select Your Manufacturer<a name="Make"></a></p>';
                continue;
            }
            
            ?>
            <a href="<?php echo $categoryHelper->getCategoryUrl($subCategory) ?>" class="<?php echo $columnsClass; ?>">
                <li class="category-item ">
                    <div class="name-container"><p class="name"><?php if($isRobot){echo $subCategory->getName().' '.$currentPageTitle;}else{echo $subCategory->getName();} ?></p></div>
                       <?php if($subCategory->getImageUrl()): ?>
                       <div class="img-container">
                            <img src="<?php echo $subCategory->getImageUrl(); ?>" alt="<?php echo $subCategory->getName().' '.$currentPageTitle; ?>"/>
                        </div>
                        <?php endif; ?>       
                </li>
            </a>
        <?php endforeach; ?>           
    </ul>

    <?php if($categoryLevel != 2): ?>
        <?php echo $block->getInformationTabsHtml(); ?>
    <?php endif; ?>
<?php endif; ?>

                                       