<div class="logos">
    <div class="footer-american-made">
        <img src="<?php echo $this->getViewFileUrl('images/made-american-footer.png'); ?>" />
    </div>
    <div class="cards">
        <p class="title"><?php echo __('We Gladly Accept') ?></p>
        <img src="<?php echo $this->getViewFileUrl('images/cc.png'); ?>" />
    </div>
    <div class="retailers">
        <p class="title"><?php echo __('Proud Retailer For') ?></p>
        <img src="<?php echo $this->getViewFileUrl('images/carver.png'); ?>" />
    </div>
    <div class="safe-shopping">
        <p class="title"><?php echo __('Safe & Secure Shopping') ?></p>
        <span id="siteseal"><script async type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=EYBHeP0HrgciRzXAVjviLCIzXmVIDOOeM9XyJRWC84pG8sO86WUaGc2WWzm9"></script></span>
        <!-- <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script> -->
    </div>
</div>
<div class="clearfix"></div>