<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// Get ?find Param
if($block->getRequest()->getParam('find')){ 
    $currentFindParam = $block->getRequest()->getParam('find');
}else{
	$currentFindParam = FALSE;
} 

// Transform URL Param Presentation for Product Title
if($currentFindParam){                
	// Category Name
	$requestURI = $block->getRequest()->getRequestUri();
	$currentPage = substr($requestURI, 0, (strrpos($requestURI,'?')));
	switch ($currentPage) {
	    case '/jet-ski-covers.html':
	        $currentTitle = 'Jet Ski Covers';
	        break; 
	}  
    
    // Fitment Title
    $fitmentTitle = '';
    $fitmentTitleArray = explode('-',$currentFindParam);
    array_pop($fitmentTitleArray);
    if(strlen(end($fitmentTitleArray)) > 4){$skipCount = 2;}else{$skipCount = 1;} // Is the last element YYYY
    if($skipCount == 1){
        $fitmentTitle = end($fitmentTitleArray);
        for($i = 0; $i < count($fitmentTitleArray) - 1; ++$i) {
            $fitmentTitle .=  ' '.$fitmentTitleArray[$i];
        }
	}else{
        for($i = 0; $i < count($fitmentTitleArray); ++$i) {
            $fitmentTitle .=  ' '.$fitmentTitleArray[$i];
        }
        //$fitmentTitle .= 'All Years '.$fitmentTitle;										
	}
	$fitmentTitle = ucwords($fitmentTitle).' ';
	
	$crumbs = array();
	$crumbs[0] = array('label' => 'Home', 'title' => 'Go to Home Page', 'link' => 'https://cover.world/');
	$crumbs[1] = array('label' => $currentTitle, 'title' => NULL, 'link' => 'https://cover.world'.$currentPage);
	$crumbs[2] = array('label' => $fitmentTitle.' Covers', 'link' => NULL, 'last' => TRUE);
} 

//var_dump($crumbs);

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
    <ul class="items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>"><?php echo $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
