<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$isRobot = ((strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "googlebot") OR $block->getRequest()->getParam('isRobotTest')))?TRUE:FALSE;

// Get ?find Param                    
if($block->getRequest()->getParam('find')){ 
    $currentFindParam = $block->getRequest()->getParam('find');
}else{
	$currentFindParam = FALSE;
} 

// Transform URL Param Presentation for Product Title
if($currentFindParam){                
	// Category Name
	$requestURI = $block->getRequest()->getRequestUri();
	$currentPage = substr($requestURI, 0, (strrpos($requestURI,'?')));
	switch ($currentPage) {
	    case '/jet-ski-covers.html':
	        $currentTitle = 'Jet Ski Covers';
	        break; 
	}  
    
    // Fitment Title
    $fitmentTitle = '';
    $fitmentTitleArray = explode('-',$currentFindParam);
    array_pop($fitmentTitleArray);
    if(strlen(end($fitmentTitleArray)) > 4){$skipCount = 2;}else{$skipCount = 1;} // Is the last element YYYY
    if($skipCount == 1){
        $fitmentTitle = end($fitmentTitleArray);
        for($i = 0; $i < count($fitmentTitleArray) - 1; ++$i) {
            $fitmentTitle .=  ' '.$fitmentTitleArray[$i];
        }
	}else{
        for($i = 0; $i < count($fitmentTitleArray); ++$i) {
            $fitmentTitle .=  ' '.$fitmentTitleArray[$i];
        }
        //$fitmentTitle .= 'All Years '.$fitmentTitle;										
	}
	$fitmentTitle = ucwords($fitmentTitle).' ';
	
	$crumbs = array();
	$crumbs[0] = array('label' => 'Home', 'title' => 'Go to Home Page', 'link' => 'https://cover.world/');
	$crumbs[1] = array('label' => $currentTitle, 'title' => NULL, 'link' => 'https://cover.world'.$currentPage);
	$crumbs[2] = array('label' => $fitmentTitle.' Covers', 'link' => NULL, 'last' => TRUE); 
} 

//var_dump($crumbs);



?>
<?php if ($crumbs && is_array($crumbs)) :
array_shift($crumbs);
$GLOBALS['breadcrumbs'] = $crumbs;
$defualtLabel = ' ';
$Category = ' ';

 ?>
<div class="breadcrumbs">
    <ul class="items">
    
    	<?php if ($isRobot) : ?>
       <li class="item home">
         <a href="https://cover.world/" title="Go to Home Page">Vehicle Covers</a>
       </li>
       <?php else: ?>
    	<li class="item home">
         <a href="https://cover.world/" title="Go to Home Page">Home</a>
       </li>
       <?php endif; ?>
       
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
            <?php if ($isRobot && $crumbInfo['link']) : 
                switch($crumbInfo['type']){
                	
                	case 'Vehicle':
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).'</a>';
                		$Vehicle = $crumbInfo['label'];
                	break;
                	
                	case 'Make':
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).' '.$Vehicle.'</a>';
                		$Make = $crumbInfo['label'];
                	break;
                	
                	case 'Model':
                		echo '<a href="'.$crumbInfo['link'].'">'.$Make.' '.$block->escapeHtml($crumbInfo['label']).' '.$Vehicle.'</a>';
                		$Model = $crumbInfo['label'];
                	break;
                	
                	case 'Year':
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).' '.$Make.' '.$Model.' '.$Vehicle.'</a>';
                		$Year = $crumbInfo['label'];
                	break;
                	
                	case 'Option':
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).' '.$Vehicle.'</a>';
                		$Option = $crumbInfo['label'];
                	break;
                	
                	case 'Category':
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).$Category.$Vehicle.'</a>';
                		$Category .= $crumbInfo['label'].' ';
                	break;
                	
                	default:
                		echo '<a href="'.$crumbInfo['link'].'">'.$block->escapeHtml($crumbInfo['label']).$defualtLabel.$Vehicle.'</a>';
                		$defualtLabel .= $crumbInfo['label'].' ';
                }
                ?>
            <?php elseif ($crumbInfo['link']) : ?>
                <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>"><?php echo $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?php echo $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
            
        <?php endforeach; ?>
    </ul>
</div>


	 <?php 
	     foreach ($crumbs as $crumbName => $crumbInfo) : 
	        if(array_key_exists('type', $crumbInfo)){$$crumbInfo['type'] = $crumbInfo['label'];} 
	     endforeach;
	      
        $imageLocation = '/pub/static/frontend/CoverWorld/default/en_US/images/';
        $bannerImageName = '';
        
        if (isset($Vehicle)){
        	
           switch($Vehicle){
	           case 'Jet Ski Covers': 
	           	$bannerImageName = 'banner-jetski.jpg';
	           break;
	           
           }      		
        }
        
        if (isset($Make)){
        	
           switch($Make){
	           case 'Arctic Cat': 
	           	$bannerImageName = 'banner-articcat.jpg';
	           break;
	           
	           case 'Honda': 
	           	$bannerImageName = 'banner-honda.jpg';
	           break;
	           
	           case 'Kawasaki': 
	           	$bannerImageName = 'banner-kawasaki.jpg';
	           break;
	           
	           case 'Polaris': 
	           	$bannerImageName = 'banner-polaris.jpg';
	           break;
	           
	           case 'Sea Doo': 
	           	$bannerImageName = 'banner-seadoo.jpg';
	           break;
	           
	           case 'Yamaha': 
	           	$bannerImageName = 'banner-yamaha.jpg';
	           break;
	           
           }
        }
	      
	?>
	<?php if($bannerImageName == ''): ?> 
		<div class="hero header-banner">
		<div class="row2"></div>
		</div>
	<?php else: ?>
		<div class="hero header-banner">
		<div class="row1"><img id="header-banner-image" src="<?php echo $imageLocation.$bannerImageName; ?>" /></div>
		<div class="row2"></div>
		</div>
	<?php endif; ?>
	
	
<?php endif; ?>
