<div class="copyright">
    <span><?php echo $block->getCopyright() ?></span> | <a href="<?php echo $this->getBaseUrl().'terms_of_use'; ?>"><?php echo __('Terms of Use') ?></a>
    <img class="sale-graphic saveupto" id="saveupto" src="<?php echo $this->getViewFileUrl('images/sale-graphic.png'); ?>" />
</div>
<div id="saveupto-modal" style="display:none;">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('saveupto')->toHtml(); ?>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var saveuptoOptions = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Factory Direct Pricing!',
                modalClass: 'best-price-popup',
                buttons:false
            };

            var saveupto = modal(saveuptoOptions, $('#saveupto-modal'));
            $("#saveupto").on('click',function(){
                $("#saveupto-modal").modal("openModal");
            });
        }
    );
</script>
