<div class="header-pre-container">
<?php echo $block->getChildHtml('header_container'); ?>
</div>
<style>
@media (max-width: 768px){
  .page-footer .footer.content .footer-links .item-links-list{
	      margin: 0px 2px;
  }
  .page-header-title{
	     margin-top: -102px !important;
  }
  .catalog-category-view .leftbar{
	  width: 32%;
  }
  .catalog-product-view .title-container{
	      margin-top: -52px;
  }
  .qualifyhovereffect .img-container .name{
	      font-size: 12px;
  }
  .catalog-product-view .product.info.detailed .data.item.content .product-details .qualifications table td .img-container{
	      width: 55px;
		  padding: 3px 5px;
  }
  .qualifyhoverdiv{
	      top: 142px;
  }
  .iner-vlooo .leftblock{
	  width:65%;
  }
  .customer-account-create .form-create-account .actions-toolbar .primary{
	  margin-bottom: 10px;
	  margin-right: 25px;
  }
  .page-layout-2columns-left .sidebar-main{
	     margin-top: 45px;
  }
  .page-layout-2columns-left .sidebar-main{
	    margin-top: 185px;
	}
	.catalog-product-view .title-container{
		  margin-top: -85px;
	}
	.page-header-change-category{
		  margin-top: 25px;
	}
}
.swatches-price-addform-container div.mage-error[generated]{
	display:block;
}
.minicart-wrapper{
	height:40px;
}
.page-header .minicart-wrapper:after{
	transform: skew(45deg);
}
.page-header .checkout-link:after {
	transform: skew(45deg);
}
.page-header .contact:after{
	transform: skew(45deg);
}
.ie11 .catalog-category-view.page-layout-1column .main.column{
	margin-top:-95px;
}
.ie11 .catalog-category-view.category-jet-ski-covers  .page-header-title{
	margin-top:-100px;
}
.ie11 .category-jet-ski-covers .page-wrapper .page-main h1{
	margin-bottom:12px;
}
.ie11 .catalog-category-view  .page-header-title{
	margin-top:0px;
}
.ie11 .catalog-category-view  .page-wrapper .page-main h1{
	margin-bottom:12px;
}
select::-ms-expand {
    display: none;
} 
@media (max-width: 1109px){
	.leftbar{
		width:23%;
	}
	.page-header-change-category{
		margin-top:25px;
	}
} 
.catalog-product-view .mfes-trustmark{
	width: 150px;
    margin-top: 25px;
}
.catalog-product-view .carver-cover{
	padding-top: 15px;
	width: auto;
}
.onestepcheckout-index-index .mfes-trustmark{
	width: 150px;
}
.page-header-alignment{float:left;margin-top:20px}

/**for ipad**/
 /* For general iPad layouts */
@media only screen and (device-width: 768px) {
.columns .column.main{
	padding-top:0px !important;
}
}
/* For portrait layouts only */
@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait) {
.columns .column.main{
	padding-top:0px !important;
}
.page-header .header.content .content-right{
	margin-right: 400px;
}
.catalog-category-view .page-header-title{
	margin-top:-16px !important;
}
.category-grid-extratop {
    margin-top: 287px !important;
}

.category-jet-ski-covers .block-categoryfilters{
	    padding-top: 60px;
}
.category-jet-ski-covers .page-header-content-less{
	    margin-top: -175px;
}

.page-products .products-grid .product-items .product-item .product-item-info .product-item-details{
	display:block;
}
/**product detail page**/
.catalog-product-view .title-container{
	margin-top:0px;
}
.page-layout-1column .product-info-main{
	width:40% !important;
}
.catalog-product-view .product-info-main .swatches-price-addform-container .product-options-wrapper .swatch-opt,.swatches-price-addform-container div.mage-error[generated]{
	float:left;
}
.catalog-product-view .product-info-main .swatches-price-addform-container .product-options-wrapper .swatch-opt{margin-top:10px;}
}
/* For landscape layouts only */
@media only screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape) {
.columns .column.main{
	padding-top:0px !important;
}
.category-grid-extratop {
    margin-top: 287px !important;
}
.page-header .header.content .content-right{
	margin-right: 400px;
}
.catalog-category-view .page-header-title{
	margin-top:0px !important;
}
.category-jet-ski-covers .page-header-cover-finder{
	margin-top: -55px;
}
.category-jet-ski-covers .block-categoryfilters{
	    padding-top: 60px;
}
.category-jet-ski-covers  .page-header-content-less{
	    margin-top: -175px;
}
.category-jet-ski-covers .page-header-material-description{
	padding-top:0px;
}
.page-products .products-grid .product-items .product-item .product-item-info .product-item-details{
	display:block;
}
/**product detail page**/
.catalog-product-view .title-container{
	margin-top:0px;
}
.page-layout-1column .product-info-main{
	width:40% !important;
}
.catalog-product-view .product-info-main .swatches-price-addform-container .product-options-wrapper .swatch-opt,.swatches-price-addform-container div.mage-error[generated]{
	float:left;
}
.catalog-product-view .product-info-main .swatches-price-addform-container .product-options-wrapper .swatch-opt{margin-top:10px;}
}
// @media only screen 
// and (min-device-width : 768px) 
// and (max-device-width : 1024px)
// and (-webkit-min-device-pixel-ratio: 2){ 
	// .category-jet-ski-covers .page-header-material-description{
	// padding-top:10px;
	// }
	// .category-jet-ski-covers .page-header-cover-finder{
	// margin-top: -90px;
	// }
// }
// @media only screen 
// and (min-device-width : 768px) 
// and (max-device-width : 1024px) 
// and (orientation : portrait)
// and (-webkit-min-device-pixel-ratio: 2) {
 	// .category-jet-ski-covers .page-header-material-description{
	// padding-top:10px;
	// }
	// .category-jet-ski-covers .page-header-cover-finder{
	// margin-top: -90px;   
	// }}
	// @media only screen 
// and (min-device-width : 768px) 
// and (max-device-width : 1024px) 
// and (orientation : landscape)
// and (-webkit-min-device-pixel-ratio: 2) {
 	// .category-jet-ski-covers .page-header-material-description{
	// padding-top:10px;
	// }
	// .category-jet-ski-covers .page-header-cover-finder{
	// margin-top: -90px;
	// }}
	// .category-jet-ski-covers .page-header-cover-finder{
	// margin-top: -65px;   
	// }	
@media only screen 
  and (min-device-width: 1024px) 
  and (max-device-width: 1366px) 
  and (-webkit-min-device-pixel-ratio: 2){
	 	.category-jet-ski-covers .page-header-material-description{
	padding-top:10px;
	}
  
  }	
  @media only screen 
  and (min-device-width: 1024px) 
  and (max-device-width: 1366px) 
  and (-webkit-min-device-pixel-ratio: 2) 
  and (orientation: portrait){
	.category-jet-ski-covers .page-header-material-description{
	padding-top:10px;
	}
	.category-jet-ski-covers .page-header-cover-finder{
	margin-top: -90px;
	}
  }
  @media only screen 
  and (min-device-width: 768px) 
  and (max-device-width: 1024px) 
  and (-webkit-min-device-pixel-ratio: 2) 
  and (orientation: portrait){
	  	.category-jet-ski-covers .page-header-cover-finder{
	margin-top: -65px;
	}
  }  
  @media only screen 
  and (min-device-width: 768px) 
  and (max-device-width: 1024px) 
  and (-webkit-min-device-pixel-ratio: 2) 
  and (orientation: landscape){
	  	.category-jet-ski-covers .page-header-cover-finder{
	margin-top: -90px;   
	}
  }
    @media only screen 
  and (min-device-width: 768px) 
  and (max-device-width: 1024px) {
 	.category-jet-ski-covers .page-header-cover-finder{
	margin-top: -90px;
	} 
  }
.product-options-bottom{
	width: 180px;
} 
</style>