<p class="title"><?php echo __('Real Customer Reviews (typos & all)') ?></p>
<ul class="reviews">
        <li class="review-item">
            <table>
                <tr>
                    <td>
                        <div class="photo-container"><img src="<?php echo $this->getViewFileUrl('images/photo-rustydumpkins.png'); ?>" /></div>
                    </td>
                    <td>
                        <p class="description">Dedicated and professional. I'm not accustomed to a product being made jut for me so I was little nervious about the extra few days. The nice gentleman in customer service assured me it was being stitched as we spoke and would be worth the wait. Boy was it ever! Uncommon quality and a great bunch of folks. Thank you!!</p>
                        <div class="review-ratings">
						<div class="rating-summary item">
						<div class="rating-box">
						<div class="rating" style="width: 96%;"></div>
						</div>
						</div>
						<p class="review-author"><span class="review-details-label">by</span> <strong class="review-details-value">rustydumpkins</strong></p>
						</div>
                    </td>
                </tr>
            </table>
        </li>
        <li class="review-item last">
            <table>
                <tr>
                    <td>
                        <div class="photo-container"><img src="<?php echo $this->getViewFileUrl('images/photo-bldeforest1.png'); ?>" /></div>
                    </td>
                    <td>      
                        <p class="description">Fast shipping,a little pricey but worth it for the quality merchandise.... my jet ski is now protected from all mother nature can dish out. Bring it... Oh and it looks sharp too.</p>
                        <div class="review-ratings">
						<div class="rating-summary item">
						<div class="rating-box">
						<div class="rating" style="width: 94%;"></div>
						</div>
						</div>
						<p class="review-author"><span class="review-details-label">by</span> <strong class="review-details-value">bldeforest1</strong></p>
						</div>
                    </td>
                </tr>
            </table>
        </li>

</ul>